FROM postgres:9.6

RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 5432/tcp

#RUN wget https://s3.amazonaws.com/openods-assets/database_backups/openods_012.dump



